// --- VUE : MES COURTIERS ---
// Grille des courtiers avec valorisation totale (extraite du fichier principal, axe 2 de l'audit).
import { PlusCircle, Trash2, Edit2, Building2 } from "lucide-react";
import { BlurMoney } from "../ui.jsx";

export const BrokersView = ({ brokers, privacyMode, getTotalByBrokerInEur, onAdd, onEdit, onDelete, onSelect }) => (
  <div className="space-y-6 w-full animate-fade-in">
    <div className="flex justify-between items-center"><h2 className="text-2xl font-bold text-gray-800 dark:text-white">Mes Courtiers</h2><button onClick={() => onAdd()} className="flex items-center gap-2 bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-700 shadow-lg font-medium transition-transform active:scale-95"><PlusCircle className="w-5 h-5" /> Ajouter</button></div>
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">{brokers.map(b => (<div key={b.id} onClick={() => { onSelect(b); }} className="bg-white dark:bg-slate-800 p-6 rounded-xl border border-gray-100 dark:border-slate-700 shadow-lg hover:shadow-2xl cursor-pointer group relative overflow-hidden transition-all"><div className="absolute top-0 right-0 w-24 h-24 bg-blue-50 dark:bg-slate-700 rounded-bl-full -mr-12 -mt-12 group-hover:scale-110 transition-transform"></div><div className="relative flex justify-between items-start mb-6"><div className="flex items-center gap-3"><div className="p-3 bg-blue-50 dark:bg-slate-700 rounded-xl group-hover:bg-blue-600 group-hover:text-white transition-colors"><Building2 className="w-6 h-6 dark:text-blue-300 group-hover:text-white" /></div><h3 className="font-bold text-lg text-gray-800 dark:text-gray-100 truncate max-w-[150px]">{b.name}</h3></div><div className="flex gap-1 z-10"><button onClick={e => { e.stopPropagation(); onEdit(b); }} className="p-2 hover:bg-gray-100 dark:hover:bg-slate-600 rounded-lg text-gray-400 hover:text-blue-600 dark:hover:text-blue-400"><Edit2 className="w-4 h-4" /></button><button onClick={e => { e.stopPropagation(); onDelete(b.id); }} className="p-2 hover:bg-red-50 dark:hover:bg-red-900/30 rounded-lg text-gray-400 hover:text-red-600 dark:hover:text-red-400"><Trash2 className="w-4 h-4" /></button></div></div><div className="relative"><div className="text-3xl font-bold text-gray-900 dark:text-white"><BlurMoney amount={getTotalByBrokerInEur(b)} privacyMode={privacyMode} /></div><div className="text-sm text-gray-500 dark:text-gray-400 font-medium mt-1">{b.accounts.length} compte(s)</div></div></div>))}</div>{!brokers.length && <div className="text-center py-20 bg-white dark:bg-slate-800 rounded-xl border-2 border-dashed border-gray-300 dark:border-slate-700"><Building2 className="w-16 h-16 text-gray-300 dark:text-slate-600 mx-auto mb-4" /><p className="text-gray-500 dark:text-gray-400 font-medium">Aucun courtier enregistré</p></div>}
  </div>
);