// --- VUE : MES COURTIERS ---
// Grille des courtiers avec valorisation totale (extraite du fichier principal, axe 2 de l'audit).
import { PlusCircle, Trash2, Edit2, Building2 } from "lucide-react";
import { BlurMoney } from "../ui.jsx";

export const BrokersView = ({ brokers, privacyMode, getTotalByBrokerInEur, onAdd, onEdit, onDelete, onSelect }) => (
  <div className="space-y-6 w-full animate-fade-in">
    <div className="flex justify-between items-center"><h2 className="text-2xl font-bold text-[#16233B] dark:text-white">Mes Courtiers</h2><button onClick={() => onAdd()} className="flex items-center gap-2 bg-[#14603B] text-white px-4 py-2 rounded-lg hover:bg-[#0F4C2F] shadow-none font-medium transition-transform active:scale-95"><PlusCircle className="w-5 h-5" /> Ajouter</button></div>
    <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">{brokers.map(b => (<div key={b.id} onClick={() => { onSelect(b); }} className="bg-[#FDFCF9] dark:bg-slate-800 p-6 rounded-xl border border-[#E4E0D6] dark:border-slate-700 shadow-none hover:shadow-2xl cursor-pointer group relative overflow-hidden transition-all"><div className="absolute top-0 right-0 w-24 h-24 bg-[#EDF3EE] dark:bg-slate-700 rounded-bl-full -mr-12 -mt-12 group-hover:scale-110 transition-transform"></div><div className="relative flex justify-between items-start mb-6"><div className="flex items-center gap-3"><div className="p-3 bg-[#EDF3EE] dark:bg-slate-700 rounded-xl group-hover:bg-[#14603B] group-hover:text-white transition-colors"><Building2 className="w-6 h-6 dark:text-emerald-300 group-hover:text-white" /></div><h3 className="font-bold text-lg text-[#16233B] dark:text-slate-100 truncate max-w-[150px]">{b.name}</h3></div><div className="flex gap-1 z-10"><button onClick={e => { e.stopPropagation(); onEdit(b); }} className="p-2 hover:bg-[#EDEAE0] dark:hover:bg-slate-600 rounded-lg text-[#8B93A1] hover:text-[#14603B] dark:hover:text-[#14603B]"><Edit2 className="w-4 h-4" /></button><button onClick={e => { e.stopPropagation(); onDelete(b.id); }} className="p-2 hover:bg-red-50 dark:hover:bg-red-900/30 rounded-lg text-[#8B93A1] hover:text-red-600 dark:hover:text-red-400"><Trash2 className="w-4 h-4" /></button></div></div><div className="relative"><div className="text-3xl font-bold text-[#16233B] dark:text-white"><BlurMoney amount={getTotalByBrokerInEur(b)} privacyMode={privacyMode} /></div><div className="text-sm text-[#6E7685] dark:text-slate-400 font-medium mt-1">{b.accounts.filter(a => !a.closed).length} compte(s){b.accounts.some(a => a.closed) ? <span className="text-[#8B93A1] dark:text-slate-500"> · {b.accounts.filter(a => a.closed).length} clôturé(s)</span> : ''}</div></div></div>))}</div>{!brokers.length && <div className="text-center py-20 bg-[#FDFCF9] dark:bg-slate-800 rounded-xl border-2 border-dashed border-[#D8D2C4] dark:border-slate-700"><Building2 className="w-16 h-16 text-[#B6BCC6] dark:text-slate-600 mx-auto mb-4" /><p className="text-[#6E7685] dark:text-slate-400 font-medium">Aucun courtier enregistré</p></div>}
  </div>
);